# Generated by Django 5.0.1 on 2024-02-08 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to='original_images/')),
                ('first_model_image', models.ImageField(blank=True, null=True, upload_to='first_model_images/')),
                ('second_model_image', models.ImageField(blank=True, null=True, upload_to='second_model_images/')),
                ('license_plate_image', models.ImageField(blank=True, null=True, upload_to='license_plate_images/')),
                ('vehicle_type', models.CharField(blank=True, max_length=200, null=True)),
                ('license_plate_text', models.CharField(blank=True, max_length=200, null=True)),
                ('license_plate_vehicle_type', models.CharField(blank=True, max_length=200, null=True)),
                ('g_print', models.TextField(blank=True, max_length=500, null=True)),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='car.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
