"""
Django settings for greencraft project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import datetime

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-3$6+yu0!j0gpn@bhmky+uwkd**x&l%si2-ut=*+v)*os^75%=5"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['10.0.2.2', 'localhost', '127.0.0.1','34.47.81.202']


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "loginapp",
    'rest_framework',
    "use_model",
    'corsheaders',
    "car",
    "manager",
    "raspi"

]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "greencraft.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "greencraft.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.oracle',
#         'NAME': 'orcl',  # Oracle DB 이름
#         'USER': 'c##greencraft6',  # Oracle 사용자 이름
#         'PASSWORD': '2030',  # Oracle 비밀번호
#         'HOST': 'localhost',  # Oracle 호스트, 로컬일 경우 'localhost'
#         'PORT': '1521',  # Oracle 포트, 기본값은 '1521'
#     }
# }
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.oracle',
        'NAME': 'xe',  # Oracle DB 이름
        'USER': 'testuser',  # Oracle 사용자 이름
        'PASSWORD': '12345',  # Oracle 비밀번호
        'HOST': '34.47.81.202',  # Oracle 호스트, 로컬일 경우 'localhost'
        'PORT': '1521',  # Oracle 포트, 기본값은 '1521'
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "ko-KR"

TIME_ZONE = "Asia/Seoul"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
GOOGLE_CLIENT_ID = '393084876973-aelpanbtkjkpbnp0erh12nfdmaeo6a9r.apps.googleusercontent.com'

AUTH_USER_MODEL = 'loginapp.CustomUser'
REST_FRAMEWORK = {

    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
}

# JWT 설정
JWT_AUTH = {
    'JWT_SECRET_KEY': SECRET_KEY,  # 서버와 클라이언트 간의 공유 비밀 키
    'JWT_ALGORITHM': 'HS256',  # 알고리즘 (일반적으로 HS256 사용)
    'JWT_ALLOW_REFRESH': True,  # 토큰 재발급 허용 여부
    'JWT_EXPIRATION_DELTA': datetime.timedelta(hours=1),  # 토큰 만료 시간
    'JWT_REFRESH_EXPIRATION_DELTA': datetime.timedelta(days=7),  # 재발급 토큰 만료 시간
}


# 미디어 파일 설정
MEDIA_ROOT = 'C:/last_project/greencraft/images'
MEDIA_URL = '/media/'
