# Generated by Django 5.0.1 on 2024-02-08 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageWithText',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('car_img', models.ImageField(upload_to='captured_images/')),
                ('bunho_img', models.ImageField(upload_to='captured_images/')),
                ('text', models.TextField()),
            ],
        ),
    ]
